CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  amount BIGINT NOT NULL
);

CREATE TABLE inventory (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(255) NOT NULL,
  stock BIGINT NOT NULL DEFAULT 100
);