spring:
  application:
    name: kafka-orders-demo

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

app:
  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT}
    consumer-group: ${KAFKA_CONSUMER_GROUP_ID}
    inventory-group: inventory-group
    aggregated-group: aggregated-group
    dlq-group: dlq-group
    notifications-group: notifications-group
    payments-group: payments-group
    orders-streams: orders-streams
    orders-topic: orders-topic
    payments-topic: payments-processed
    inventory-topic: inventory-updated
    notifications-topic: notifications
    aggregated-topic: aggregated-orders
    dlq-topic: dlq-topic
